name: Test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        id: install-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ vars.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        id: setup-pnpm-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        id: install-packages
        run: pnpm install

      - name: Run code checks
        run: pnpm check

      - name: Run tests
        run: pnpm test

      - name: Build & generate examples
        run: pnpm generate

      - name: Save examples
        uses: actions/upload-artifact@v3
        with:
          name: example-documents
          path: examples
          retention-days: 3
